# Generated by Django 2.1.7 on 2019-03-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('json', models.TextField()),
            ],
            options={
                'ordering': ('-datetime',),
                'get_latest_by': 'datetime',
            },
        ),
    ]
